### ISSUE TITLE
Heroku error 

### ISSUE THREAD

**Issue by youngda** [nassir-malik/IOT-ESP8266-Google-Home#3]
2018-02-02T01:15:10.953284+00:00 app[web.1]: ValueError: Line without CRLF
2018-02-02T01:15:10.953544+00:00 app[web.1]: Task exception was never retrieved
2018-02-02T01:15:10.953547+00:00 app[web.1]: future: <Task finished coro=<HttpWSSProtocol.handler() done, defined at app.py:10> exception=ValueError('Line without CRLF',)>
2018-02-02T01:15:10.953549+00:00 app[web.1]: Traceback (most recent call last):
2018-02-02T01:15:10.953550+00:00 app[web.1]:   File "app.py", line 12, in handler
2018-02-02T01:15:10.953552+00:00 app[web.1]:     request_line, headers = await websockets.http.read_message(self.reader)
2018-02-02T01:15:10.953554+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/websockets/http.py", line 83, in read_message
2018-02-02T01:15:10.953555+00:00 app[web.1]:     start_line = yield from read_line(stream)
2018-02-02T01:15:10.953557+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/websockets/http.py", line 107, in read_line
2018-02-02T01:15:10.953558+00:00 app[web.1]:     raise ValueError("Line without CRLF")
2018-02-02T01:15:10.953560+00:00 app[web.1]: ValueError: Line without CRLF

2018-02-02T05:09:37.669102+00:00 app[web.1]: ('Line without CRLF',)
2018-02-02T05:10:14.186102+00:00 heroku[router]: at=error code=H13 desc="Connection closed without response" method=POST path="/" host=wwwtestman.herokuapp.com request_id=85a48efa-443c-4a30-a5e6-040a69828d8e fwd="35.192.55.231" dyno=web.1 connect=0ms service=4ms status=503 bytes=0 protocol=https
2018-02-02T05:10:14.185329+00:00 app[web.1]: 'result'
2018-02-02T05:11:48.695761+00:00 app[web.1]: ('Line without CRLF',)

**Comment by pqekypk2** [comment]
i have the same issue

**Comment by isharaux** [comment]
Anyone found a fix for this?

**Comment by isharaux** [comment]
Possible cause for this might be client sending an HTTP request rather than a web socket,
Try following for sending a client side web socket to server,

`
# WS client example

import asyncio
import websockets
import json

async def hello():
    uri = "ws://localhost:5687/ws"
    async with websockets.connect(uri) as websocket:
        sample_data = {"location": "living", "state": "on", "device": "lights"}
        await websocket.send(json.dumps(sample_data))
        print(f"> {sample_data}")

        resp = await websocket.recv()
        print(f"< {resp}")

asyncio.get_event_loop().run_until_complete(hello())`

**Comment by arcslash** [comment]
The JSON structure has been changed from the google assistant side, make sure to change your python script accordingly
